#executable for easy use
#!/usr/bin/env python

#run the program


python python/main.py AAL AAP AAPL ABT ADI ADP ADSK AFL AIZ ALGN ALXN AMAT AMD AMGN AMZN APHA APPF ASML ATO ATR ATVI AUY AVGO BA BABA BAC BCPC BDX BIDU BIIB BKNG BLV BMRN BNTX BOND  BP BR BRK-B BYND CB  CBPO CCL CDNS CDW CERN CGC CHK CHKP CHTR CINF CL CLX  CMCSA COST CPRX CRBP CRM CRON CSCO CSX CTAS CTSH CTXS CVX DAL DIS DLTR DTE EA EBAY EGP EMR ET ETR EVBG EXC EXPE FAST FB FINT FISV FIT GBIL GILD GLUU GOOG GOOGL GPRO GRPN HAE HAL HAS HCA HLT HSIC IDXX IJS ILMN INO INTC INTU ISRG IT IVE IWD IYF JAZZ JBHT JBLU JD JNJ JNUG JPM KHC KLAC KMB KO LBTYA LEG LK LMT LRCX LSTR LULU LUV LYFT MAR MCD MCHP MDLZ MDT MELI MFA MGM MJ MMM MNST MO MRNA MRO MSA MSFT MTB MU MXIM MYL NCLH NDAQ NFLX NIO NKE NLOK NOK NRZ NTAP NTDOY NTES NVAX NVDA NVRO NXPI NYMT OPK ORLY OXY PAYX PCAR PCG PENN PEP PFE PLUG PM PTON PYPL QCOM RCL REGN RGA ROKU ROST RPG RTN SAVE SBUX SIRI SMG SNAP SNE SNPS SO SPCE SPHD SPY SQ SRPT SUB SWKS SYY T TCEHY TCOM TGT TLRY TMUS TROW TRV TSLA TTWO TWTR TXN UAL UBER UHS ULTA UTX V VAW VIG VIOO VKTX VOO VRSK VRSN VRTX VSLR VTI VZ WBA WDAY WDC WM WMT WORK WYNN XEL XLNX XLY XOM ZM ZNGA





# python python/main.py AAL AAP AAPL ABT ADI ADP ADSK AFL AIZ ALGN ALXN AMAT AMD AMGN AMZN APHA APPF ASML ATR ATVI AUY AVGO BABA BAC

#python python/main.py HLT FB GOOG DIS MSFT GPRO FIT SNAP CCL PLUG  DAL INO CHK CRON UBER  CGC NCLH BA TWTR GRPN SBUX RCL ZNGA T NIO UAL KO  MFA VSLR MRNA XOM NFLX LK SPCE TLRY NVDA NRZ VOO MRO PENN SQ LYFT NOK SPY CPRX NKE WORK V JBLU SIRI ZM JNUG BYND MGM HAL NTDOY BRK-B LUV CSCO CRBP INTC PFE ET VKTX GLUU SPHD GOOGL ROKU VTI MU OXY WMT JPM PTON PCG JNJ SNE NYMT PYPL
#
#python python/main.py OPK TCEHY CRM MJ GILD BP VZ NVAX LMT MCD MDT MMM MO BDX CVX CB CINF CLX CL EMR EXC XOM HAS KMB LEG PAYX PEP PFE PM PGADI BIDU BIIB BMRN CDNS CERN CHKP CHTR TCOM CTAS CTXS CMCSA COST CSX CTSH DLTR EA EBAY EXPE FAST FISV HSIC ILMN INTU
#
#python python/main.py ISRG IDXX JBHT JD KLAC KHC LRCX LBTYA LULU MELI MAR MCHP MDLZ MNST MU MXIM MYL NTAP NTES NXPI ORLY PCAR BKNG QCOM REGN ROST RTN SWKS NLOK SNPS SO SYY TGT TTWO TSLA TXN TMUS ULTA UTX VRSN VRSK VRTX WBA WDC WDAY WM WYNN XEL XLNX SAVE
#
#python python/main.py HCA UHS NVRO MSA ETR CBPO DTE RGA HAE EGP IYF VAW IJS VIOO ATO IWD IVE TRV RPG SRPT MTB IT CDW TROW SMG NDAQ XLY JAZZ VIG EVBG LSTR BCPC FINT BR BOND BLV GBIL SUB

