#executable for easy use
#!/usr/bin/env python

#run the program
python python/main.py HLT FB GOOG DIS MSFT GPRO AAPL FIT SNAP AAL CCL PLUG BAC DAL INO CHK CRON UBER AMD CGC NCLH BA TWTR GRPN SBUX RCL ZNGA BABA T NIO APHA UAL KO AMZN MFA VSLR MRNA XOM NFLX LK SPCE TLRY NVDA NRZ VOO MRO PENN SQ LYFT NOK SPY CPRX NKE WORK V JBLU SIRI ZM JNUG BYND MGM HAL NTDOY BRK-B LUV CSCO CRBP INTC PFE ET VKTX GLUU SPHD ATVI AUY GOOGL ROKU VTI MU OXY WMT JPM PTON PCG JNJ SNE NYMT PYPL

python python/main.py OPK TCEHY CRM MJ GILD BP VZ NVAX LMT MCD MDT MMM ABT AFL MO ADP BDX CVX CB CINF CLX CL EMR EXC XOM HAS KMB LEG PAYX PEP PFE PM PG ALGN ALXN AMGN ADI AMAT ASML ADSK AVGO BIDU BIIB BMRN CDNS CERN CHKP CHTR TCOM CTAS CTXS CMCSA COST CSX CTSH DLTR EA EBAY EXPE FAST FISV HSIC ILMN INTU


python python/main.py ISRG IDXX JBHT JD KLAC KHC LRCX LBTYA LULU MELI MAR MCHP MDLZ MNST MU MXIM MYL NTAP NTES NXPI ORLY PCAR BKNG QCOM REGN ROST RTN SWKS NLOK SNPS SO SYY TGT TTWO TSLA TXN TMUS ULTA UTX VRSN VRSK VRTX WBA WDC WDAY WM WYNN XEL XLNX SAVE

