#executable for easy use
#!/usr/bin/env python

#run the program
python python/main.py FB GOOG DIS MSFT GPRO AAPL FIT SNAP AAL CCL PLUG BAC DAL INO CHK CRON UBER AMD CGC NCLH BA FB TWTR GRPN SBUX RCL ZNGA BABA T NIO APHA UAL KO AMZN MFA VSLR MRNA XOM NFLX LK SPCE TLRY NVDA NRZ VOO MRO PENN SQ LYFT NOK SPY CPRX NKE WORK V JBLU SIRI ZM JNUG BYND SAVE MGM HAL NTDOY BRK-B LUV CSCO CRBP INTC PFE ET VKTX GLUU SPHD ATVI AUY GOOGL ROKU VTI MU OXY WMT JPM PTON PCG JNJ SNE NYMT PYPL OPK TCEHY CRM MJ GILD BP VZ NVAX 

